examen_3/tercer_punto/gestor/urls.py
from django.contrib import admin
from django.urls import path
from gestor import views

urlpatterns = [
	
	path('', views.inicio, name='inicio_view'),

	# Listas
	path('personal_list/', views.personal_list.as_view(), name='personal_list_view'),
	path('reuniones_list/', views.reuniones_list.as_view(), name='reuniones_list_view'),
	path('actividades_list/', views.actividades_list.as_view(), name='actividades_list_view'),
	path('proyectos_list/', views.proyectos_list.as_view(), name='proyectos_list_view'),
	path('clientes_list/', views.clientes_list.as_view(), name=' clientes_list_view'),
	path('avances_list/', views.avances_list.as_view(), name='avances_list_view'),
	path('pruebas/<str:slug>', views.pruebas.as_view(), name = 'pruebas_list_view'),
	# Detalles
	path('detalle_avance/<int:pk>', views.detalle_avance.as_view(), name = 'detalle_avance_view'),
	path('detalle_personal/<nombre_personal>', views.detalle_personal.as_view(), name = 'detalle_personal_view'),
	path('detalle_actividad/<int:pk>',views.detalle_actividad.as_view(), name = 'detalle_actividad_view'),
	path('detalle_proyecto/<int:pk>', views.detalle_proyecto.as_view(), name = 'detalle_proyecto_view'),
]

examen_3/tercer_punto/tercer_punto/urls.py
from django.contrib import admin
from django.urls import path, include
from gestor import urls as urls_gestor

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(urls_gestor)),
]

examen_3/tercer_punto/gestor/models.py
from django.db import models
# Create your models here.

class Estados(models.Model):
	estado = models.CharField(max_length = 20)
	fecha_registro = models.DateTimeField(auto_now_add = True)
	def __str__(self):
		return str(self.estado)

class Cargos(models.Model):
	nombre_cargo = models. CharField(max_length = 20)
	descripcion = models.CharField(max_length = 100)
	fecha_registro = models.DateTimeField(auto_now_add = True)
	def __str__(self):
		return str(self.nombre_cargo)

class Sexos(models.Model):
	sexo = models.CharField(max_length = 20)
	fecha_registro = models.DateTimeField(auto_now_add = True)
	def __str__(self):
		return str(self.sexo)

class Empresas(models.Model):
	nombre_empresas = models.CharField(max_length = 40)
	fecha_registro = models.DateTimeField(auto_now_add = True)
	def __str__(self):
		return str(self.nombre_empresas)

class Proyectos(models.Model):
	nombre_proyecto = models.CharField(max_length = 40)
	descripcion = models.CharField(max_length = 100)
	estado = models.ForeignKey(Estados, on_delete=models.CASCADE)
	fecha_registro = models.DateTimeField(auto_now_add = True)
	def __str__(self):
		return str(self.nombre_proyecto)

class Personal(models.Model):
	nombre_personal = models.CharField(max_length = 40)
	edad = models.IntegerField()
	sexo = models.ForeignKey(Sexos, on_delete=models.CASCADE)
	telefono = models.IntegerField()
	cargo = models.ForeignKey(Cargos, on_delete=models.CASCADE)
	fecha_registro = models.DateTimeField(auto_now_add = True)
	def __str__(self):
		return str(self.nombre_personal)

class Proyecto_Empleado(models.Model):
	nombre_proyecto = models.ForeignKey(Proyectos, on_delete=models.CASCADE)
	nombre_personal = models.ForeignKey(Personal, on_delete=models.CASCADE)
	fecha_registro = models.DateTimeField(auto_now_add = True)
	def __str__(self):
		return str(self.nombre_proyecto)

class Proyecto_Lider(models.Model):
	nombre_proyecto = models.ForeignKey(Proyectos, on_delete=models.CASCADE)
	nombre_personal = models.ForeignKey(Personal, on_delete=models.CASCADE)
	fecha_registro = models.DateTimeField(auto_now_add = True)
	def __str__(self):
		return str(self.nombre_proyecto)		

class Avances(models.Model):
	nombre_avance = models.CharField(max_length = 40)
	nombre_proyecto = models.ForeignKey(Proyectos, on_delete=models.CASCADE)
	descripcion = models.CharField(max_length = 100)
	fecha_entrega = models.DateTimeField()
	estado = models.ForeignKey(Estados, on_delete=models.CASCADE)
	fecha_registro = models.DateTimeField(auto_now_add = True)
	def __str__(self):
		return str(self.nombre_avance)

class Actividades(models.Model):
	nombre_avance = models.ForeignKey(Avances, on_delete=models.CASCADE)
	nombre_actividad = models.CharField(max_length = 40)
	descripcion = models.CharField(max_length = 100)
	fecha_entrega = models.DateTimeField()
	estado = models.ForeignKey(Estados, on_delete=models.CASCADE)
	fecha_registro = models.DateTimeField(auto_now_add = True)
	def __str__(self):
		return str(self.nombre_actividad)

class Actividad_Personal(models.Model):
	nombre_actividad = models.ForeignKey(Actividades, on_delete=models.CASCADE)
	nombre_personal = models.ForeignKey(Personal, on_delete=models.CASCADE)
	fecha_registro = models.DateTimeField(auto_now_add = True)
	def __str__(self):
		return str(self.nombre_actividad)	

class Reuniones(models.Model):
	nombre_reunion = models.CharField(max_length = 40)
	nombre_proyecto = models.ForeignKey(Proyectos, on_delete=models.CASCADE)
	lugar = models.CharField(max_length = 100)
	descripcion = models.CharField(max_length = 100)
	fecha_reunion = models.DateTimeField()
	fecha_registro = models.DateTimeField(auto_now_add = True)
	def __str__(self):
		return str(self.nombre_reunion)

class Clientes(models.Model):
	nombre_cliente = models.CharField(max_length = 40)
	edad = models.IntegerField()
	sexo = models.ForeignKey(Sexos, on_delete=models.CASCADE)
	telefono = models.IntegerField()
	empresa = models.ForeignKey(Empresas, on_delete=models.CASCADE)
	fecha_registro = models.DateTimeField(auto_now_add = True)
	def __str__(self):
		return str(self.nombre_cliente)

class Reunion_Cliente(models.Model):
	nombre_reunion = models.ForeignKey(Reuniones, on_delete=models.CASCADE)
	nombre_cliente = models.ForeignKey(Clientes, on_delete=models.CASCADE)
	fecha_registro = models.DateTimeField(auto_now_add = True)
	def __str__(self):
		return str(self.nombre_reunion)

class Reunion_Personal(models.Model):
	nombre_reunion = models.ForeignKey(Reuniones, on_delete=models.CASCADE)
	nombre_personal = models.ForeignKey(Personal, on_delete=models.CASCADE)
	fecha_registro = models.DateTimeField(auto_now_add = True)
	def __str__(self):
		return str(self.nombre_reunion)

examen_3/tercer_punto/gestor/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.db.models import Q
from .models import Estados
from .models import Cargos
from .models import Sexos
from .models import Empresas
from .models import Proyectos
from .models import Personal
from .models import Proyecto_Empleado
from .models import Proyecto_Lider		
from .models import Avances
from .models import Actividades
from .models import Actividad_Personal	
from .models import Reuniones
from .models import Clientes
from .models import Reunion_Cliente
from .models import Reunion_Personal
# Create your views here.

def inicio(request):
	return render(request, "gestor/inicio.html")

# Listas
class personal_list(generic.ListView):
	template_name = "gestor/personal.html"
	queryset = Personal.objects.all()

class proyectos_list(generic.ListView):
	template_name = "gestor/proyectos.html"
	queryset = Proyectos.objects.all()

class actividades_list(generic.ListView):
	template_name = "gestor/actividades.html"
	queryset = Actividades.objects.order_by('fecha_entrega')

class avances_list(generic.ListView):
	template_name = "gestor/avances.html"
	queryset = Avances.objects.all()

class clientes_list(generic.ListView):
	template_name = "gestor/clientes.html"
	queryset = Clientes.objects.all()

class reuniones_list(generic.ListView):
	template_name = "gestor/reuniones.html"
	queryset = Reuniones.objects.all()

# Detalles

class detalle_proyecto(generic.DetailView):
 	template_name = "gestor/detalle_proyecto.html"
 	model = Proyectos

class detalle_avance(generic.DetailView):
 	template_name = "gestor/detalle_avance.html"
 	model = Avances

class detalle_actividad(generic.DetailView):
 	template_name = "gestor/detalle_actividad.html"
 	model = Actividades

class detalle_personal(generic.DetailView):
 	template_name = "gestor/detalle_personal.html"
 	model = Personal

 	def get_object(self):
 		return get_object_or_404(Personal, nombre_personal__iexact=self.kwargs.get("nombre_personal"))

class pruebas(generic.DetailView):
 	template_name = "gestor/pruebas.html"
 	model = Proyectos

# def detalle_proyecto(request, id=1):
# 	proyecto = Proyectos.objects.get(id=id)
# 	contexto = {
# 	"proyecto" : proyecto
# 	}
# 	return render(request, "gestor/detalle_proyecto.html", contexto)

examen_3/tercer_punto/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS and JS -->
    
    <link rel="stylesheet" href="{% static 'bootstrap4/css/bootstrap.min.css' %}">


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    
    <script src="{% static 'bootstrap4/js/bootstrap.min.js' %}"></script>

    <title>{% block title %}{% endblock %} </title>
  </head>
  
  
  <!-- posible imagen de fondo -->

      <img class="img-fluid" src='/static/Images/Fondo_Principal.jpg'>


  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <a class="navbar-brand" href="{% url 'inicio_view'%}">Parra's Inc.</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'proyectos_list_view'%}">Proyectos<span class="sr-only">(current)</span></a>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link" href="#">Calendario</a>
        </li> -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'personal_list_view'%}">Personal</a>
       </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'reuniones_list_view'%}">Reuniones</a>
        </li>       
        <!-- <li class="nav-item">
          <a class="nav-link" href="{% url 'avances_list_view'%}">Avances</a>
        </li> -->
        <!-- <li class="nav-item">
          <a class="nav-link" href="#">Extra</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Extra</a>
        </li> -->
        <!-- Dropdown del calendario -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarNavDropdownMenuLink3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Calendarios</a>
          <div class="dropdown-menu" aria-labelledy="navbarNavDropdownMenuLink3">
            <a class="dropdown-item" href="{% url 'actividades_list_view'%}">Calendario de actividades</a>
            <a class="dropdown-item" href="{% url 'avances_list_view'%}">Calendario de avances</a>
          </div>
        </li>
        <!-- Dropdown de reportes o algo asi... meh -->
        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarNavDropdownMenuLink2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Reportes</a>
          <div class="dropdown-menu" aria-labelledy="navbarNavDropdownMenuLink2">
            <a class="dropdown-item" href="#">Lista de Reportes</a>
            <a class="dropdown-item" href="#">Crear Reporte</a>
          </div>
        </li> -->
        
        <!-- trash -->
        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarNavDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Registrar</a>
          <div class="dropdown-menu" aria-labelledy="navbarNavDropdownMenuLink">
            <a class="dropdown-item" href="#">Registrar Jugador</a>
            <a class="dropdown-item" href="#">Registrar Equipo</a>
            <a class="dropdown-item" href="#">Registrar Estadio</a>
            <a class="dropdown-item" href="#">Registrar Asiento</a>
            <a class="dropdown-item" href="#">Registrar Fanatico</a>
             <a class="dropdown-item" href="#">Rentar Palco</a>
          </div>
        </li> -->
      </ul>
   </div>
  </nav>
    {% block content %}

    {% endblock %}
    
  </body>
</html>

examen_3/tercer_punto/templates/gestor/actividades.html
{% extends 'base.html' %}
{% block title %} Actividades {% endblock %}

{% block content %}

<section class="container">
	<table class="table table-strip mt-5">
		<th>nombre de la actividad</th>
		<th>Fecha de entrega</th>
		<th>Estado</th>
		{% for j in object_list %}
			<tr>
				<td>{{ j.nombre_actividad }} </td>
				<td>{{ j.fecha_entrega }}</td>
				<td>{{ j.estado }}</td>
				<td><a href="#" class="btn btn-dark">Detalle</a></td>
				<td><a href="#" class="btn btn-dark">Actualizar</a></td>
			</tr>

			{% empty %}
			{% if request.GET.q %}
				No se entontro avance
			{% else %}
				No hay datos
			{% endif %}
		{% endfor %}
	</table>  
</section>
{% endblock %}

examen_3/tercer_punto/templates/gestor/avances.html
{% extends 'base.html' %}
{% block title %} Avances {% endblock %}

{% block content %}

<section class="container">
	<table class="table table-strip mt-5">
		<th>Nombre del avance</th>
		<th>Fecha de entrega</th>
		<th>Proyecto</th>
		{% for j in object_list %}
			<tr>
				<td>{{ j.nombre_avance }} </td>
				<td>{{ j.fecha_entrega }}</td>
				<td>{{ j.nombre_proyecto }}</td>
				<td><a href="{% url 'detalle_avance_view' j.id%}" class="btn btn-dark">Detalle</a></td>
				<td><a href="#" class="btn btn-dark">Actualizar</a></td>
			</tr>

			{% empty %}
			{% if request.GET.q %}
				No se entontro avance
			{% else %}
				No hay datos
			{% endif %}
		{% endfor %}
	</table>  
</section>
{% endblock %}

examen_3/tercer_punto/templates/gestor/clientes.html
{% extends 'base.html' %}
{% block title %} Clientes {% endblock %}

{% block content %}

<section class="container">
	<table class="table table-strip mt-5">
		<th>Nombre</th>
		<th>Empresa</th>
		{% for j in object_list %}
			<tr>
				<td>{{ j.nombre_cliente }} </td>
				<td>{{ j.empresa }}</td>
				<td><a href="#" class="btn btn-dark">Detalle</a></td>
				<td><a href="#" class="btn btn-dark">Actualizar</a></td>
			</tr>

			{% empty %}
			{% if request.GET.q %}
				No se entontro clientes
			{% else %}
				No hay datos
			{% endif %}
		{% endfor %}
	</table>  
</section>
{% endblock %}

examen_3/tercer_punto/templates/gestor/detalle_actividad.html
{% extends 'base.html' %}

{% block title %} detalle actividad {% endblock %}

{% block content %}
<section class="container mt-5">
	<div>
		<h1 class="text-center">{{object.nombre_actividad}}</h1>
		<p class="text-justify">Descripcion: {{object.descripcion}}</p>

		<table class="table table-strip mt-5">
			<th>Personal encargado</th>
			{%for personal in object.actividad_personal_set.all %}
				<tr>
						<td>{{ personal.nombre_personal }} </td>
						<td><a href="{% url 'detalle_personal_view' personal.nombre_personal%}" class="btn btn-dark">Detalle</a></td>
						<td><a href="#" class="btn btn-dark">Actualizar</a></td>
				</tr>

					{% empty %}
					{% if request.GET.q %}
						No se entontro clientes
					{% else %}
						No hay datos
					{% endif %}
			{% endfor %}
	</table>
</section>
{% endblock %}

examen_3/tercer_punto/templates/gestor/detalle_avance.html
{% extends 'base.html' %}

{% block title %} detalle_avance {% endblock %}

{% block content %}
<section class="container mt-5">
	<div>
		<h1 class="text-center">{{object.nombre_avance}}</h1>
		<p class="text-justify">Proyecto: {{object.nombre_proyecto}}</p>

		<table class="table table-strip mt-5">
			<th>Actividades del avance</th>
			<th>Fecha de realización</th>
			{%for actividad in object.actividades_set.all %}
				<tr>
						<td>{{ actividad.nombre_actividad }} </td>
						<td>{{ actividad.fecha_entrega }} </td>
						<td><a href="{% url 'detalle_actividad_view' actividad.id%}" class="btn btn-dark">Detalle</a></td>
						<td><a href="#" class="btn btn-dark">Actualizar</a></td>
				</tr>

					{% empty %}
					{% if request.GET.q %}
						No se entontro clientes
					{% else %}
						No hay datos
					{% endif %}
			{% endfor %}
	</table>
</section>
{% endblock %}

examen_3/tercer_punto/templates/gestor/detalle_personal.html
{% extends 'base.html' %}

{% block title %} detalle personal{% endblock %}

{% block content %}
<section class="container mt-5">
	<div>
		<h1 class="text-center">{{object.nombre_personal}}</h1>
		<p class="text-justify">Edad: {{object.edad}}</p>
		<p class="text-justify">Sexo: {{object.sexo}}</p>
		<p class="text-justify">Telefono: {{object.telefono}}</p>
		<p class="text-justify">Cargo: {{object.cargo}}</p>
</section>
{% endblock %}

examen_3/tercer_punto/templates/gestor/detalle_proyecto.html
{% extends 'base.html' %}

{% block title %} detalle_proyecto {% endblock %}

{% block content %}
<section class="container mt-5">
	<div>
		<h1 class="text-center">{{object.nombre_proyecto}}</h1>
		<p class="text-justify">Descripcion: {{object.descripcion}}</p>

		<table class="table table-strip mt-5">
			<th>Personal dentro del proyecto</th>
			{%for personal in object.proyecto_empleado_set.all %}
				<tr>	
						<td>{{ personal.id }} </td>
						<td>{{personal.nombre_personal}}</td>
						<td><a href="{% url 'detalle_personal_view' personal.nombre_personal %}" class="btn btn-dark">Detalle</a></td>
						<td><a href="#" class="btn btn-dark">Actualizar</a></td>
				</tr>

					{% empty %}
					{% if request.GET.q %}
						No se entontro clientes
					{% else %}
						No hay datos
					{% endif %}
			{% endfor %}
	</table>
</section>
{% endblock %}

examen_3/tercer_punto/templates/gestor/inicio.html
{% extends 'base.html' %}

{% block title %} Parra's Inc. {% endblock %}

{% block content %}
	<section class="container">
		<div class="jumbotron mt-5">
			<h1 class="display-4 text-center">Pagina de Inicio</h1>
			<p class="text-center">proximamente...</p>
		</div>
	</section>    
{% endblock %}

examen_3/tercer_punto/templates/gestor/personal.html
{% extends 'base.html' %}
{% block title %} Personal {% endblock %}

{% block content %}

<section class="container">
	<table class="table table-strip mt-5">
		<th>Nombre</th>
		<th>Cargo</th>
		{% for j in object_list %}
			<tr>
				<td>{{ j.nombre_personal }} </td>
				<td>{{ j.cargo }}</td>
				<td><a href="{% url 'detalle_personal_view' j.nombre_personal%}" class="btn btn-dark">Detalle</a></td>
				<td><a href="#" class="btn btn-dark">Actualizar</a></td>
			</tr>

			{% empty %}
			{% if request.GET.q %}
				No se entontro personal
			{% else %}
				No hay datos
			{% endif %}
		{% endfor %}
	</table>  
</section>
{% endblock %}

examen_3/tercer_punto/templates/gestor/proyectos.html
{% extends 'base.html' %}
{% block title %} Proyectos {% endblock %}

{% block content %}

<section class="container">
	<table class="table table-strip mt-5">
		<th>Proyecto</th>
		<th>Estado</th>
		{% for j in object_list %}
			<tr>
				<td>{{ j.nombre_proyecto }} </td>
				<td>{{ j.estado }}</td>
				<td><a href="{%url 'detalle_proyecto_view' j.id%}" class="btn btn-dark">Detalle</a></td>
				<td><a href="#" class="btn btn-dark">Actualizar</a></td>
			</tr>

			{% empty %}
			{% if request.GET.q %}
				No se entontro avance
			{% else %}
				No hay datos
			{% endif %}
		{% endfor %}
	</table>  
</section>
{% endblock %}

examen_3/tercer_punto/templates/gestor/pruebas.html
{% extends 'base.html' %}

{% block title %} detalle_proyecto {% endblock %}

{% block content %}
<section class="container mt-5">
	<div>
		<h1 class="text-center">{{object.nombre_proyecto}}</h1>
		<p class="text-justify">Descripcion: {{object.descripcion}}</p>

		<table class="table table-strip mt-5">
			<th>Personal dentro del proyecto</th>
			{%for personal in object.proyecto_empleado_set.all %}
				<tr>
						<td>{{ personal.nombre_personal }} </td>
						<td><a href="{% url 'detalle_personal_view' personal.id%}" class="btn btn-dark">Detalle</a></td>
						<td><a href="#" class="btn btn-dark">Actualizar</a></td>
				</tr>

					{% empty %}
					{% if request.GET.q %}
						No se entontro clientes
					{% else %}
						No hay datos
					{% endif %}
			{% endfor %}
	</table>
</section>
{% endblock %}

examen_3/tercer_punto/templates/gestor/reuniones.html
{% extends 'base.html' %}
{% block title %} Reuniones {% endblock %}

{% block content %}

<section class="container">
	<table class="table table-strip mt-5">
		<th>Lugar</th>
		<th>fecha de reunión</th>
		{% for j in object_list %}
			<tr>
				<td>{{ j.lugar }} </td>
				<td>{{ j.fecha_reunion }}</td>
				<td><a href="#" class="btn btn-dark">Detalle</a></td>
				<td><a href="#" class="btn btn-dark">Actualizar</a></td>
			</tr>

			{% empty %}
			{% if request.GET.q %}
				No se entontro reunion
			{% else %}
				No hay datos
			{% endif %}
		{% endfor %}
	</table>  
</section>
{% endblock %}